export const createMeeshoOrderTable = `
CREATE TABLE IF NOT EXISTS oms."meeshoOrders" (
	id serial4 NOT NULL,
	"userId" int4 NOT NULL,
	"orderNumber" varchar(255) NOT NULL,
	"subOrderNumber" varchar(255) NULL,
	"productName" varchar(255) NULL,
	"productSku" varchar(255) NULL,
	"productId" varchar(255) NULL,
	variation varchar(50) NULL,
	quantity int4 NULL,
	expected_dispatch_date date NULL,
	"slaStatus" varchar(50) NULL,
	status varchar(50) NULL,
	"orderType" varchar(50) NULL,
	"orderedDate" timestamp NULL,
	"createdAt" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"subOrderIdentifier" varchar(255) NULL,
	"returnType" varchar(50) NULL,
	"returnSubType" varchar(50) NULL,
	"shipmentStatus" varchar(50) NULL,
	"expectedDeliveryDateISO" timestamp NULL,
	"lastAttemptedDateISO" timestamp NULL,
	"carrierName" varchar(255) NULL,
	"carrierIdentifier" varchar(255) NULL,
	"carrierAccountType" varchar(50) NULL,
	"trackingURL" text NULL,
	awb varchar(255) NULL,
	"returnPriceType" varchar(50) NULL,
	"returnDetailedReason" text NULL,
	"returnReason" text NULL,
	"reverseOfdAttemptCountValue" int4 NULL,
	"reverseOfdAttemptCountLabel" varchar(50) NULL,
	"firstAttemptedDateISO" timestamp NULL,
	"proofOfDeliveryLabel" varchar(50) NULL,
	"displayMsg" varchar(50) NULL,
	"otpVerifiedFlag" bool NULL,
	"otpVerifiedTime" timestamp NULL,
	"digitalPodURL" text NULL,
	"digitalPodExpiryTime" int4 NULL,
	"orderDispatchDateISO" timestamp NULL,
	"orderDeliveredDateISO" timestamp NULL,
	"paymentDate" timestamp NULL,
	amount varchar NULL,
	penalty varchar NULL,
	netamount varchar NULL,
	returnshippingcharge varchar NULL,
	CONSTRAINT "meeshoOrders_pkey" PRIMARY KEY (id),
	CONSTRAINT unique_order_sub_order UNIQUE ("orderNumber", "subOrderNumber")
);
`;
